language: java

jdk:
  - oraclejdk7

env:
  global:
  - GH_REF: github.com/dita4publishers/docs
  - BRANCH: master
  - DITA_DIR: DITA-OT1.8.5 
  - CLASSPATH: $DITA_DIR/lib/:$DITA_DIR/lib/dost.jar:$DITA_DIR/lib/commons-codec-1.4.jar:$DITA_DIR/lib/resolver.jar:lib/icu4j.jar:$DITA_DIR/lib/xercesImpl.jar:$DITA_DIR/lib/xml-apis.jar:$DITA_DIR/lib/saxon/saxon9.jar:$DITA_DIR/lib/saxon/saxon9-dom.jar
  - ANT_HOME: $DITA_DIR/tools/ant PATH=$DITA_DIR/tools/ant/bin:$PATH
  - D4P_REPO: https://github.com/dita4publishers/dita4publishers.git
  - D4P_DIR: dita4publishers
  - DITA_REPO: http://sourceforge.net/projects/dita-ot/files/DITA-OT%20Stable%20Release/DITA%20Open%20Toolkit%201.8/DITA-OT1.8.5_full_easy_install_bin.tar.gz/download
  - secure: 'ddd'

after_success:
  - cd ~/$D4P_DIR
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push

script: bash ./script.sh