language: java

jdk:
  - oraclejdk7

env:
  global:
  - GH_REF: github.com/dita4publishers/docs
  - BRANCH: master
  - DOC_DIR: docs
  - WEBSITE_DOC_MAP: docs/user_docs/d4p-users-guide.ditamap
  - D4P_REPO: https://github.com/dita4publishers/dita4publishers.git
  - D4P_DIR: dita4publishers
  - secure: 'to be filled later'

script: bash ./script.sh

after_success:
  - cd ~/$DOC_DIR
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push
